# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imcdesign2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(306, 311)
        MainWindow.setStyleSheet("")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(80, 10, 151, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 67, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit.setGeometry(QtCore.QRect(70, 160, 51, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(180, 130, 67, 13))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 160, 51, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(120, 200, 75, 23))
        self.pushButton.clicked.connect(self.calculo)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(75, 250, 300, 40))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setGeometry(QtCore.QRect(65, 60, 81, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 90, 51, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 90, 51, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(MainWindow)
        self.label_6.setGeometry(QtCore.QRect(190, 60, 47, 13))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def calculo(self):

        self.peso = float(self.lineEdit.text())
        self.altura = float(self.lineEdit_2.text())
        self.gen = str(self.lineEdit_3.text()).upper()
        self.idade = int(self.lineEdit_4.text())
        self.imcval = self.peso / (self.altura ** 2)

        categorias = {"M": { 1 : [19.6, 18.2, 14.5],
                             2 : [18.7, 17.4, 14.0],
                             3 : [18.2, 17.0, 13.4],
                             4 : [18.0, 16.7, 13.2],
                             5 : [18.1, 16.7, 13.0],
                             6 : [18.4, 16.9, 13.2],
                             7 : [18.7, 17.2, 13.3],
                             8 : [19.4, 17.5, 13.5],
                             9 : [20.1, 18.0, 13.6],
                            10 : [28.6, 25.0, 17.5], # Conferir esses valores
                            11 : [22.0, 19.3, 14.2],
                            12 : [23.0, 20.0, 14.6],
                            13 : [24.2, 21.0, 15.0],
                            14 : [25.3, 21.9, 15.6],
                            15 : [26.4, 22.8, 16.2],
                            16 : [27.3, 23.7, 16.7],
                            17 : [28.0, 24.5, 17.2],
                            18 : [28.6, 25.0, 17.5],
                            19 : [30.0, 25.0, 18.5],},

                      "F": { 1 : [19.4, 17.9, 13.9],
                             2 : [18.5, 17.2, 13.5],
                             3 : [18.2, 16.8, 13.2],
                             4 : [18.3, 16.8, 13.0],
                             5 : [18.6, 17.0, 12.8],
                             6 : [18.9, 17.1, 12.8],
                             7 : [19.5, 17.4, 12.9],
                             8 : [20.1, 17.8, 13.0],
                             9 : [21.0, 18.5, 13.3],
                            10 : [22.0, 19.1, 13.6],
                            11 : [23.2, 20.0, 14.0],
                            12 : [24.4, 20.9, 14.5],
                            13 : [25.6, 22.0, 15.1],
                            14 : [26.6, 22.9, 15.6],
                            15 : [27.6, 23.6, 16.1],
                            16 : [28.3, 24.3, 16.4],
                            17 : [28.6, 24.6, 16.6],
                            18 : [28.9, 24.9, 16.7],
                            19 : [30.0, 24.9, 18.5],},
            }

        if self.idade > 18:
            idade_ref = 19
        else:
            idade_ref = self.idade


        if self.imcval > categorias[self.gen][idade_ref][0]:
            self.label_4.setText(str(f"O seu IMC é {self.imcval:.2f} e tem \nobesidade"))
            
        elif self.imcval >= categorias[self.gen][idade_ref][1]:
            self.label_4.setText(str(f"O seu IMC é {self.imcval:.2f} e tem \nsobrepeso"))
            
        elif self.imcval >= categorias[self.gen][idade_ref][2]:
            self.label_4.setText(str(f"O seu IMC é {self.imcval:.2f} e tem \num peso normal"))
            
        else:
            self.label_4.setText(str(f"O seu IMC é {self.imcval:.2f} e tem \num peso abaixo do normal"))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.label.setText(_translate("MainWindow", "CALCULADORA DE IMC"))
        self.label_2.setText(_translate("MainWindow", "Peso(Kg)"))
        self.label_3.setText(_translate("MainWindow", "Altura(m)"))
        self.pushButton.setText(_translate("MainWindow", "CALCULAR"))
        self.label_5.setText(_translate("MainWindow", "Gênero(M/F)"))
        self.label_6.setText(_translate("MainWindow", "Idade"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec_()
